### PR TITLE
Fix5

### PR DESCRIPTION
**Pull request by JanWeidnerPTW**
See #5

### CODE REVIEW

**Comment by JeffreySarnoff** [comment]
Jan
Good! I will prepare and run an all permutations test on each of the first 16 over the weekend.

**Comment by JanWeidnerPTW** [comment]
I was curious how long this would take on my machine. 45 days (single thread).
```juliarepl
julia> @benchmark swapsort(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p)
BenchmarkTools.Trial: 
  memory estimate:  144 bytes
  allocs estimate:  1
  --------------
  minimum time:     186.923 ns (0.00% GC)
  median time:      190.528 ns (0.00% GC)
  mean time:        208.271 ns (1.97% GC)
  maximum time:     1.452 μs (82.17% GC)
  --------------
  samples:          10000
  evals/sample:     661

julia> factorial(16) * (186e-9) / 60 /60 /24 # days
45.04211712
```

**Comment by JeffreySarnoff** [comment]
Either you are using an abacus or I need a new game plan.

**Comment by JeffreySarnoff** [comment]
As these routines do as little as possible (or aspire to that, and come close), I think any routine that were not entirely correct would show us that with relatively small sampling from the set of all permutations.  Testing all is best, no question. I will update this thread when I have new information.

**Comment by JanWeidnerPTW** [comment]
You could use the [0-1 principle](http://www.iti.fh-flensburg.de/lang/algorithmen/sortieren/networks/nulleinsen.htm). With this you only have `2^16=65536` cases. That could even run with the unit tests in no time.

**Comment by JeffreySarnoff** [comment]
Clearly, it is time to apply  this "indispensable tool" -- how is that done?

**Comment by JanWeidnerPTW** [comment]
```julia
using SortingNetworks
using Base.Test
using Iterators
tf = (true, false)
for N in 1:16
    for seq in product(Base.Iterators.repeated(tf, N)...)
        res = swapsort(seq)
        @test issorted(res)
    end
end
```

**Comment by JanWeidnerPTW** [comment]
I even think if one puts effort in making this type stable it could run up to N=25 with the regular CI.

**Comment by JeffreySarnoff** [comment]
There is a new end-of-the-readme:

acknowledgement

Jan Weidner provided provably correct code to test each implementation.

**Pull request merged**
